# Generated by Django 6.0.3 on 2026-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('Age', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('Education', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(height_field=50, null=True, upload_to='Pictures', width_field=50)),
            ],
        ),
    ]
